language: node_js
node_js:
  - '8.2.1'
os:
  - linux
dist: trusty
install:
  - yarn install --frozen-lockfile
script:
  - yarn transpile
  - yarn lint
  - yarn test-node
  - yarn nsp check
  - yarn generate
  - yarn prepare-beta-build
  - $(yarn bin)/build --config.extraMetadata.environment=$SIGNAL_ENV --config.mac.bundleVersion='$TRAVIS_BUILD_NUMBER' --publish=never
  - ./travis.sh
env:
  global:
    - SIGNAL_ENV: production
sudo: false
notifications:
  email: false
